---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box
    require_chef_omnibus: true
  attributes:
    designate:
      rabbitmq_hosts:
        - 127.0.0.1:5672

suites:
- name: central
  run_list: ["recipe[designate::central]"]
- name: api
  run_list: ["recipe[designate::api]"]
- name: agent
  run_list: ["recipe[designate::agent]"]
- name: sink
  run_list: ["recipe[designate::sink]"]
